### ISSUE TITLE
Student Sign Up

### ISSUE THREAD

**Issue by zthaver** [zthaver/Enrollment-System#3]
Student sign up should generate a unique username for the students to go and sign in. Users must provide an email and a password that satisifies certain criteria. users will be emailed a username that  will be uniquely generated by the system

**Comment by joshuaduke** [comment]
Student will enter their first name, last name, email, password, password confirmation. The system will validate all field to ensure that they meet the criteria and provide an accurate error message if not. Once user has successfully signed up they will be stored in the database and they will receive a confirmation email.
